import { ReportName, ReportType } from '../types/report';

export const scheduleEmployeeNameContent = [
  { name: 'John Doe', status: 'available' },
  { name: 'Jane Smith', status: 'engaged' },
  { name: 'Alice Johnson', status: 'available' },
  { name: 'Bob Brown', status: 'engaged' },
  { name: 'Emily Davis', status: 'available' },
];
// export const reportType = [
//   { name: 'View DS' },
//   { name: 'ESI Report' },
//   { name: 'EPF Report' },
//   { name: 'PTAX Report' },
//   { name: 'Without Allowance' },
//   { name: 'New Payroll' },
//   { name: 'DSL Report' },
//   { name: 'L&T Report' },
//   { name: 'Others' },
//   { name: 'Salary Report' },
//   // { name: 'Custom' },
// ];

export const reportType: ReportType[] = [
  { type: 0, name: ReportName.NONE, reportCode: 'NONE' },
  { type: 1, name: ReportName.VIEW_DS_REPORT, reportCode: 'VIEW_DS_REPORT' },
  { type: 2, name: ReportName.ESI_REPORT, reportCode: 'ESI_REPORT' },
  { type: 3, name: ReportName.EPF_REPORT, reportCode: 'EPF_REPORT' },
  { type: 4, name: ReportName.PTAX_REPORT, reportCode: 'PTAX_REPORT' },
  {
    type: 5,
    name: ReportName.WITHOUT_ALLOWANCE_REPORT,
    reportCode: 'WITHOUT_ALLOWANCE_REPORT',
  },
  {
    type: 6,
    name: ReportName.NEW_PAYROLL_REPORT,
    reportCode: 'NEW_PAYROLL_REPORT',
  },
  { type: 7, name: ReportName.DSL_REPORT, reportCode: 'DSL_REPORT' },
  { type: 8, name: ReportName.LNT_REPORT, reportCode: 'LNT_REPORT' },
  { type: 9, name: ReportName.OTHERS_REPORT, reportCode: 'OTHERS_REPORT' },
  { type: 10, name: ReportName.SALARY_REPORT, reportCode: 'SALARY_REPORT' },
];
// const columns = [
//   { name: 'empName', label: 'Name & Details' },
//   { name: 'days', label: 'Days' },
//   { name: 'basicSalary', label: 'Basic Pays' },
//   { name: 'allowances', label: 'Allowances' },
//   { name: 'grossPay', label: 'Gross Pay' },
//   { name: 'extraDuty', label: 'Extra Duty' },
//   { name: 'deduction', label: 'Deduction' },
//   { name: 'other', label: 'Other' },
//   { name: 'otherDeduction', label: 'Other Deduction' },
//   { name: 'totalDeduction', label: 'Total Deduction' },
//   { name: 'netPay', label: 'Net Pay' },
//   { name: 'sign', label: 'Sign' },
// ];

export const esialwaysVisibleColumns = [
  'accNo',
  'empName',
  'days',
  'grossPay',
  'empESI',
  'emplrESI',
  'sign',
];

export const esiColumnData = [
  { name: 'accNo', label: 'Account No.' },
  { name: 'empName', label: 'Name' },
  { name: 'days', label: 'No. of Days' },
  { name: 'grossPay', label: 'Gross Pay' },
  { name: 'empESI', label: 'Employee Contribution' },
  { name: 'emplrESI', label: 'Employer Contribution' },
  { name: 'sign', label: 'Sign' },
];

export const esiRowData = [
  {
    accNo: '1234567890',
    empName: 'John Doe',
    days: 30,
    grossPay: 5000,
    empESI: 1000,
    emplrESI: 2000,
  },
];
/////////////////////////
export const withoutAllowanceVisibleColumns = [
  'empName',
  'days',
  'basicSalary',
  'extraDuty',
  'deduction',
  'other',
  'bonus',
  'otherDeduction',
  'totalDeduction',
  'netPay',
  'sign',
];
export const withoutAllowanceColumnData = [
  { name: 'empName', label: 'Name' },
  { name: 'days', label: 'Days' },
  { name: 'basicSalary', label: 'Basic Pay' },
  { name: 'extraDuty', label: 'Extra Duty' },
  { name: 'deduction', label: 'Deduction' },
  { name: 'other', label: 'Other' },
  { name: 'bonus', label: 'Bonus' },
  { name: 'otherDeduction', label: 'Other Deduction' },
  { name: 'totalDeduction', label: 'Total Deduction' },
  { name: 'netPay', label: 'Net Pay' },
  { name: 'sign', label: 'Sign' },
];

export const withoutAllowanceRowData = [
  {
    empName: 'John Doe',
    days: 30,
    basicSalary: 5000,
    extraDuty: 200,
    deduction: {
      empESI: 50,
      empEPF: 300,
      adv: 100,
      pTax: 100,
    },
    other: {
      belt: 50,
      boot: 50,
      uniform: 150,
    },
    bonus: 100,
    otherDeduction: 100,
    totalDeduction: 100,
    netPay: 5000,
  },
];
///////////////////////////
export const newPayrollVisibleColumns = [
  'empName',
  // 'rank',
  'days',
  'basicSalary',
  'uniform',
  'bonus',
  'total',
  'extraDuty',
  'deduction',
  'empEPF',
  'empESI',
  'emplrEPF',
  'emplrESI',
  'pTax',
  'otherDeduction',
  'totalDeduction',
  'netPay',
  'sign',
];
export const newPayrollColumnData = [
  { name: 'empName', label: 'Name & Rank' },
  { name: 'days', label: 'Days' },
  { name: 'basicSalary', label: 'Basic Pay' },
  { name: 'uniform', label: 'Uniform' },
  { name: 'bonus', label: 'Bonus' },
  { name: 'total', label: 'Total' },
  { name: 'extraDuty', label: 'Extra Duty' },
  { name: 'deduction', label: 'Deduction' },
  // { name: 'empEPF', label: 'Employee EPF' },
  // { name: 'empESI', label: 'Employee ESI' },
  // { name: 'emplrEPF', label: 'Employer EPF' },
  // { name: 'emplrESI', label: 'Employer ESIP' },
  { name: 'pTax', label: 'P Tax' },
  { name: 'otherDeduction', label: 'Other Deduction' },
  { name: 'totalDeduction', label: 'Total Deduction' },
  { name: 'netPay', label: 'Net Pay' },
  { name: 'sign', label: 'Sign' },
];

export const newPayrollRowData = [
  {
    empName: 'John Doe',
    rank: 'Manager',
    days: 30,
    basicSalary: 5000,
    uniform: 150,
    bonus: 100,
    total: 5500,
    extraDuty: 200,
    deduction: {
      empEPF: 300,
      empESI: 50,
      emplrEPF: 200,
      emplrESI: 100,
    },
    // empEPF: 300,
    // empESI: 50,
    // emplrEPF: 200,
    // emplrESI: 100,
    pTax: 100,
    otherDeduction: 100,
    totalDeduction: 1200,
    netPay: 4450,
  },
];
//////////////////////////////
export const DSLReportVisibleColumns = [
  'empName',
  // 'rank',
  'days',
  'eightHourPay',
  'vda',
  'uniform',
  'hra',
  'total',
  'extraDuty',
  'adv',
  'deduction',
  'empEPF',
  'pTax',
  'empESI',
  'emplrEPF',
  'emplrESI',
  'totalDeduction',
  'netPay',
  'sign',
];

export const DSLReportColumnData = [
  { name: 'empName', label: 'Name & Details' },
  { name: 'days', label: 'Days' },
  { name: 'eightHourPay', label: '8 Hour Pay' },
  { name: 'vda', label: 'VDA' },
  { name: 'uniform', label: 'Uniform' },
  { name: 'hra', label: 'HRA' },
  { name: 'total', label: 'Total' },
  { name: 'extraDuty', label: 'Extra Duty' },
  { name: 'adv', label: 'Advance' },
  { name: 'deduction', label: 'Deduction' },
  // { name: 'empEPF', label: 'Employee EPF' },
  // { name: 'empESI', label: 'Employee ESI' },
  // { name: 'emplrEPF', label: 'Employer EPF' },
  // { name: 'emplrESI', label: 'Employer ESIP' },
  { name: 'totalDeduction', label: 'Total Deduction' },
  { name: 'netPay', label: 'Net Pay' },
  { name: 'sign', label: 'Sign' },
];

export const DSLReportRowData = [
  {
    empName: 'John Doe',
    rank: 'Manager',
    days: 30,
    eightHourPay: 5000,
    vda: 150,
    uniform: 150,
    hra: 2150,
    total: 5650,
    extraDuty: 200,
    adv: 100,
    deduction: {
      empEPF: 300,
      pTax: 50,
      empESI: 50,
      emplrEPF: 200,
      emplrESI: 100,
    },
    totalDeduction: 1200,
    netPay: 4450,
    // empEPF: 300,
    // empESI: 50,
    // emplrEPF: 200,
  },
];
//////////////////////////
export const lstvisibleColumns = [
  'empName',
  // 'rank',
  'days',
  'eightHourPay',
  'vda',
  'uniform',
  'specialAllowance',
  'weeklyOff',
  'total',
  'extraDuty',
  'adv',
  'deduction',
  'empEPF',
  'pTax',
  'empESI',
  'emplrEPF',
  'emplrESI',
  'totalDeduction',
  'netPay',
];

export const lstColumnData = [
  { name: 'empName', label: 'Name & Rank' },
  { name: 'days', label: 'Days' },
  { name: 'eightHourPay', label: '8 Hour Pay' },
  { name: 'vda', label: 'VDA' },
  { name: 'uniform', label: 'Uniform' },
  { name: 'specialAllowance', label: 'Special Allowance' },
  { name: 'weeklyOff', label: 'Weekly Off' },
  { name: 'total', label: 'Total' },
  { name: 'extraDuty', label: 'Extra Duty' },
  { name: 'adv', label: 'Advance' },
  { name: 'deduction', label: 'Deduction' },
  { name: 'totalDeduction', label: 'Total Deduction' },
  { name: 'netPay', label: 'Net Pay' },
  // { name: 'empEPF', label: 'Employee EPF' },
  // { name: 'empESI', label: 'Employee ESI' },
  // { name: 'emplrEPF', label: 'Employer EPF' },
  // { name: 'emplrESI', label: 'Employer ESIP' },
];

export const lstReportRowData = [
  {
    empName: 'John Doe',
    rank: 'Manager',
    days: 30,
    eightHourPay: 5000,
    vda: 150,
    uniform: 150,
    specialAllowance: 150,
    weeklyOff: 0,
    total: 5650,
    extraDuty: 200,
    adv: 100,
    deduction: {
      empEPF: 300,
      pTax: 50,
      empESI: 50,
      emplrEPF: 200,
      emplrESI: 100,
    },
    totalDeduction: 1200,
    netPay: 4450,
    // empEPF: 300,
    // empESI: 50,
    // emplrEPF: 200,
  },
];

//////////////////////////

export const otherReportVisibleColumns = [
  'empName',
  'days',
  'basicSalary',
  'allowance',
  'grossPay',
  'extraDuty',
  'uniform',
  'fourHourPay',
  'specialAllowance',
  'bonus',
  'deduction',
  'netPay',
];

export const otherReportColumnData = [
  { name: 'empName', label: 'Name' },
  { name: 'days', label: 'Days' },
  { name: 'basicSalary', label: 'Basic Pay' },
  { name: 'allowance', label: 'Allowance' },
  { name: 'grossPay', label: 'Gross Pay' },
  { name: 'extraDuty', label: 'Extra Duty' },
  { name: 'uniform', label: 'Uniform' },
  { name: 'fourHourPay', label: '4 Hour Pay' },
  { name: 'specialAllowance', label: 'Special Allowance' },
  { name: 'bonus', label: 'Bonus' },
  { name: 'deduction', label: 'Deduction' },
  { name: 'totals', label: 'Total' },
  { name: 'netPay', label: 'Net Pay' },
];

export const otherReportRowData = [
  {
    empName: 'John Doe',
    days: 30,
    basicSalary: 5000,
    allowance: {
      kitAllowances: 1500,
      cityAllowances: 2000,
      convHra: 2150,
    },
    grossPay: 5650,
    extraDuty: 200,
    uniform: 150,
    fourHourPay: 300,
    specialAllowance: 150,
    bonus: 100,
    deduction: {
      empEPF: 300,
      empESI: 50,
      belt: 50,
      adv: 200,
      pTax: 100,
      Uniform: 100,
    },
    // totals: 1200,
    netPay: 4450,
  },
];

// const esirowData = [
//   {
//     empName: 'John Doe',
//     days: 30,
//     basicSalary: 5000,
//     allowances: {
//       kitAllowances: 1500,
//       cityAllowances: 2000,
//       convHra: 2150,
//     },
//     grossPay: 5650,
//     extraDuty: 200,
//     deduction: {
//       empESI: 50,
//       empEPF: 300,
//       adv: 100,
//       pTax: 100,
//     },
//     other: {
//       belt: 50,
//       boot: 50,
//       uniform: 150,
//     },
//     otherDeduction: 100,
//     totalDeduction: 1200,
//     netPay: 4450,
//   },
//   {
//     empName: 'Jane Doe',
//     days: 30,
//     basicSalary: 5000,
//     allowances: {
//       kitAllowances: 1500,
//       cityAllowances: 2000,
//       convHra: 2150,
//     },
//     grossPay: 5650,
//     extraDuty: 200,
//     deduction: {
//       empESI: 50,
//       empEPF: 300,
//       adv: 100,
//       pTax: 100,
//     },
//     other: {
//       belt: 50,
//       boot: 50,
//       uniform: 150,
//     },
//     otherDeduction: 100,
//     totalDeduction: 1200,
//     netPay: 4450,
//   },
// ];
